### ISSUE TITLE
大佬 大佬有没有看过验证码登录呀？抓包一个周就过期很麻烦

### ISSUE THREAD

**Issue by yzzhe** [ZengHaoCoding/huluwa#1]

**Comment by ZengHaoCoding** [comment]
小程序的验证码登入，抓包很简单，主要携带的参数也就几个，但是其中一个参数需要微信那边的账号某个授权码，并且是实时更新的，麻烦的很，这个自我感觉破解不了，这套认证的逻辑是比较完整、安全的

**Comment by yzzhe** [comment]
好的  感谢大佬
