### ISSUE TITLE
加密规则貌似不对

### ISSUE THREAD

**Issue by wms888** [ZengHaoCoding/huluwa#2]
我试了下 还是报sign不对

**Comment by ZengHaoCoding** [comment]
有两个可能吧
一个是，小程序解包出来的那个ak/sk码不对了，给他们那边后台更改了
另外一个是，你用的加密方法不是基于cypto.js库的hmac-sha256加密
你可以直接解包一个小程序看看他现在的ak/sk码对不对来排除看看
